### ISSUE TITLE
Sample config is invalid

### ISSUE THREAD

**Issue by yisraelU** [retel-io/ari-proxy#6]
# Bug Report

corresponding commit-id:latest
asterisk version:latest
kafka version:2.0
java version:8

## failure description
When running the  application via 
``` 
java -Dconfig.file=service.conf  -jar target/ari-proxy-0.9.0-fat.jar 
```
  , it exits saying no config websocket-uri is found , on closer inspection the ServiceConfig class doesnt have a asterisk-uri field only a websocket-uri field.
It would seem to be that the sample config file is inaccurate
## expected behaviour description
to run

**Comment by vinzens** [comment]
Hi, could you please post your service config (please do not post your IP Addresses and passwords as they are) 
I will test it and give some feedback. the config is working on our environment. maybe our documentation needs some update on this matter.

**Comment by vinzens** [comment]
i just tested it.
please try
```java -Dconfig.file=./service.conf  -jar target/ari-proxy-0.9.0-fat.jar ```
seems java does not look into the correct folder.

**Comment by yisraelU** [comment]
yes , it works now. 
Now i am wondering why , as there is no websocket-uri config

**Comment by vinzens** [comment]
If you have a look into the bundled application.conf we have same variable used for REST and Web socket. Since the ARI Proxy is supposed to run on a single Asterisk and both values are the same. If you need both settings changed in a different way you can change it in the application.conf for now. We haven't seen any reason to have different host configuration for the Web socket and Rest interface.
Do you?

**Comment by vinzens** [comment]
This issue is done, so i will close it. If you see any reason why we should have different configuration option for rest and Web socket, please open new feature request.
thanks

**Comment by yisraelU** [comment]
no . just when i saw the error I mistakenly concluded that was the problem. All is good now :) 
Is there a way tonfigure the http port that the proxy listens on?

**Comment by vinzens** [comment]
you can change the default-http-port in here
https://github.com/retel-io/ari-proxy/blob/master/src/main/resources/application.conf

we maybe we will get this config to the service.conf as well, so it's better to customize.

**Comment by vinzens** [comment]
i opened a feature request in order to extract the http port from application.conf
https://github.com/retel-io/ari-proxy/issues/7
