### ISSUE TITLE
How to import ari-proxy into Eclipse?

### ISSUE THREAD

**Issue by mohimoradi** [retel-io/ari-proxy#82]
We wrote an Eclipse plugin and are now collecting a database of large Akka Java Maven projects. I tried to import ari-proxy into Eclipse, but I couldn't compile it and run the tests. I Just imported the ari-proxy as an existing maven project in eclipse but it shows 50 errors like the below samples:

![image](https://user-images.githubusercontent.com/81889496/151059946-85362c72-287b-4760-9929-d55210aff60f.png)

I tried changing the java version or maven version, adding that plugin to maven dependencies, and following all of the StackOverflow suggestions, such as removing the.m2 folder, but none of them worked.

Is ari-proxy Eclipse compatible? Is it possible to run their test classes inside Eclipse? If so, what procedure should I follow?

**Comment by mohimoradi** [comment]
Okay, here is my solution:

The error is "The package java.util is accessible from more than one module".
In eclipse set the java compiler to 1.8 then change all four usages of list.of to Arrays.list like below example:

REGISTRY.counter(PROCESSOR_RESTARTS_METRIC_NAME, Arrays.asList(Tag.of("processorType", "commandResponse")));
//REGISTRY.counter(PROCESSOR_RESTARTS_METRIC_NAME, List.of(Tag.of("processorType", "commandResponse")));

Note: ari-proxy can be compiled in command prompt using Java 17 and maven 3.8.1.

**Comment by mia-krause** [comment]
Hi Mohsen,

please understand that we are not able to provide IDE specific help. Thank you for sharing your solution though! 💐
