### ISSUE TITLE
Client example

### ISSUE THREAD

**Issue by michelpelletier07** [retel-io/ari-proxy#84]
Hello.  Thank you for providing ari-proxy to the community.  I need help to get started.  Could you direct me to a java sample client program, preferably using akka, that connects to kafka and retrieves the Stasis start event and sends a few simple commands to Asterisk?  For example Answer, then play a media file, and then Hangup.  Many thanks.

**Comment by mia-krause** [comment]
Hi Michel,
we do not have a sample project yet, but there is something in progress from another contributor. Stay tuned 😄

**Comment by vinzens** [comment]
Please have a look here.
https://github.com/vinzens81/retel-controller

please also respect, we cannot provide any further help creating an Akka based client.
